import { Question, QuizCategory } from './types';

export const CATEGORIES: QuizCategory[] = [
  {
    id: 'all',
    name: 'Mixed Bag (All)',
    icon: 'Shuffle',
    description: 'A random assortment of questions across all categories.',
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'tech',
    name: 'Computer Science',
    icon: 'Cpu',
    description: 'Web development, cybersecurity, hardware, and coding trivia.',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'science',
    name: 'Science & Nature',
    icon: 'FlaskConical',
    description: 'Physics, chemistry, biology, space, and planet earth.',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'history',
    name: 'History & Geography',
    icon: 'Globe',
    description: 'Ancient civilisations, world maps, capitals, and historic events.',
    color: 'from-red-500 to-rose-600',
  },
  {
    id: 'sports',
    name: 'Sports & Entertainment',
    icon: 'Trophy',
    description: 'Olympics, famous movies, pop culture, and sports records.',
    color: 'from-purple-500 to-pink-600',
  },
];

export const LOCAL_QUESTIONS: Question[] = [
  // TECH / COMPUTER SCIENCE (20 items)
  {
    id: 'tech_1',
    question: 'Which of the following is NOT an operating system?',
    options: ['Linux', 'Windows', 'Oracle', 'macOS'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'Oracle is a database software company, whereas Linux, Windows, and macOS are functioning operating systems.',
  },
  {
    id: 'tech_2',
    question: 'What does "HTML" stand for?',
    options: [
      'HighText Markup Language',
      'HyperText Markup Language',
      'HyperTabular Markup Language',
      'HighTransition Machine Language',
    ],
    correctAnswerIndex: 1,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'HTML stands for HyperText Markup Language, the standard markup language used to structure pages on the web.',
  },
  {
    id: 'tech_3',
    question: 'Which HTTP status code represents "Internal Server Error"?',
    options: ['404', '403', '500', '502'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'medium',
    explanation: 'HTTP 500 is the standard response representing an unexpected condition that prevented the server from fulfilling the request.',
  },
  {
    id: 'tech_4',
    question: 'In JavaScript, what is the value of: typeof NaN ?',
    options: ['"undefined"', '"null"', '"number"', '"string"'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'hard',
    explanation: 'Although NaN stands for "Not a Number", its JavaScript type is technically "number".',
  },
  {
    id: 'tech_5',
    question: 'Who is regarded as the first computer programmer for her work on Babbage\'s Analytical Engine?',
    options: ['Grace Hopper', 'Ada Lovelace', 'Margaret Hamilton', 'Joan Clarke'],
    correctAnswerIndex: 1,
    category: 'tech',
    difficulty: 'medium',
    explanation: 'Ada Lovelace was an English mathematician who wrote the first algorithm intended to be executed by an early computing machine.',
  },
  {
    id: 'tech_6',
    question: 'What is the runtime complexity of finding an item in a balanced binary search tree of size N?',
    options: ['O(1)', 'O(log N)', 'O(N)', 'O(N log N)'],
    correctAnswerIndex: 1,
    category: 'tech',
    difficulty: 'medium',
    explanation: 'Each comparison in a balanced BST halves the search space, yielding logarithmic time complexity or O(log N).',
  },
  {
    id: 'tech_7',
    question: 'What is the main purpose of the "git clone" command?',
    options: ['Delete repository', 'Create local copy of remote repo', 'Check code quality', 'Publish website'],
    correctAnswerIndex: 1,
    category: 'tech',
    difficulty: 'easy',
    explanation: '"git clone" downloads an existing Git repository to your local machine to begin hacking.',
  },
  {
    id: 'tech_8',
    question: 'Which programming language uses the ".py" expression file extension?',
    options: ['JavaScript', 'Ruby', 'Python', 'C++'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'Python source code files traditionally utilize the ".py" extension.',
  },
  {
    id: 'tech_9',
    question: 'What does "CSS" stand for in web engineering?',
    options: ['Computer Style Sheets', 'Creative Style Sheets', 'Cascading Style Sheets', 'Colorful Style Sheets'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'CSS stands for Cascading Style Sheets, used to style document layouts on pages.',
  },
  {
    id: 'tech_10',
    question: 'What does "SQL" stand for in relational databases?',
    options: ['Structured Query Language', 'Simple Queue List', 'System Query Logic', 'Strong Query Link'],
    correctAnswerIndex: 0,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'SQL is the standard language for relational database query and manipulation.',
  },
  {
    id: 'tech_11',
    question: 'In database transaction logic, what does "ACID" stand for?',
    options: [
      'Atomicity, Consistency, Isolation, Durability',
      'Access, Control, Index, Data',
      'Application, Core, Integration, Deployment',
      'Authentication, Cipher, Integrity, Detection',
    ],
    correctAnswerIndex: 0,
    category: 'tech',
    difficulty: 'hard',
    explanation: 'ACID describes database transactions properties ensuring durability and isolated outcomes.',
  },
  {
    id: 'tech_12',
    question: 'Which hardware device connects distinct computer networks to the broader World Wide Web?',
    options: ['Switch', 'Router', 'Hub', 'Repeater'],
    correctAnswerIndex: 1,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'A router forwards data packets between separate computer networks, enabling outer link ingress.',
  },
  {
    id: 'tech_13',
    question: 'What is the primary function of the Domain Name System (DNS)?',
    options: ['To encrypt files', 'Translate domain names to IP addresses', 'Store email accounts', 'Server graphic visual assets'],
    correctAnswerIndex: 1,
    category: 'tech',
    difficulty: 'medium',
    explanation: 'DNS serves as the directory matching domain names to internet protocol address locations.',
  },
  {
    id: 'tech_14',
    question: 'What node model representing documents as trees is manipulated in client browsers?',
    options: ['API', 'JSON', 'DOM', 'SDK'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'medium',
    explanation: 'Document Object Model (DOM) represents web pages as trees of node elements accessible to JavaScript.',
  },
  {
    id: 'tech_15',
    question: 'Who is regarded as the father of modern theoretical computer science?',
    options: ['Bill Gates', 'Steve Jobs', 'Alan Turing', 'Tim Berners-Lee'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'Alan Turing formalized algorithms and machine computation models with the Turing Machine.',
  },
  {
    id: 'tech_16',
    question: 'What is the standard network port number allocated to secure HTTPS web traffic?',
    options: ['80', '21', '443', '8080'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'medium',
    explanation: 'HTTPS secure transmissions utilize public port 443 by default for encrypted SSL/TLS traffic.',
  },
  {
    id: 'tech_17',
    question: 'Which datatype in JavaScript represents an ordered list of zero or more values?',
    options: ['Object', 'String', 'Array', 'Boolean'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'Arrays are ordered data datasets structured under standard numeric indices starting at 0.',
  },
  {
    id: 'tech_18',
    question: 'In codebase architecture, what does the "DRY" design principle imply?',
    options: ['Don\'t Repeat Yourself', 'Do React Yearly', 'Database Recovery Yields', 'Developer Relations Youth'],
    correctAnswerIndex: 0,
    category: 'tech',
    difficulty: 'easy',
    explanation: 'Don\'t Repeat Yourself (DRY) encourages reduction of code duplication during modular design.',
  },
  {
    id: 'tech_19',
    question: 'Which classic cryptographic hash algorithm produces 40-character hexadecimal strings?',
    options: ['MD5', 'SHA-1', 'AES-256', 'RSA'],
    correctAnswerIndex: 1,
    category: 'tech',
    difficulty: 'hard',
    explanation: 'SHA-1 produces a 160-bit digest often rendered as a 40-digit hexadecimal string representing integrity indices.',
  },
  {
    id: 'tech_20',
    question: 'Which network layer protocol provides reliable, ordered, error-checked data delivery?',
    options: ['UDP', 'IP', 'TCP', 'ICMP'],
    correctAnswerIndex: 2,
    category: 'tech',
    difficulty: 'hard',
    explanation: 'Transmission Control Protocol (TCP) manages connection setups, flow control, and receipt acknowledgments.',
  },

  // SCIENCE & NATURE (20 items)
  {
    id: 'sci_1',
    question: 'What is the chemical symbol for Gold?',
    options: ['Go', 'Au', 'Ag', 'Gd'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'The chemical symbol for Gold is Au, derived from the Latin word "aurum", which means shining dawn.',
  },
  {
    id: 'sci_2',
    question: 'Which planet in our solar system has the most visible ring system?',
    options: ['Jupiter', 'Saturn', 'Neptune', 'Uranus'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Saturn has the largest and most complex ring system, composed mostly of ice particles and rocky debris.',
  },
  {
    id: 'sci_3',
    question: 'What is the powerhouse of the cell?',
    options: ['Nucleus', 'Ribosome', 'Mitochondrion', 'Endoplasmic Reticulum'],
    correctAnswerIndex: 2,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Mitochondria function as metabolic powerhouses, converting nutrients into adenosine triphosphate (ATP) for energy.',
  },
  {
    id: 'sci_4',
    question: 'What is the speed of light in a vacuum?',
    options: [
      'Approx. 150,000 km/s',
      'Approx. 300,000 km/s',
      'Approx. 450,000 km/s',
      'Approx. 600,000 km/s',
    ],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'medium',
    explanation: 'The speed of light is precisely 299,792 kilometers per second (approx. 300,000 km/s or 186,000 miles/second).',
  },
  {
    id: 'sci_5',
    question: 'Which of the following organic compounds is responsible for the green color in plant leaves?',
    options: ['Carotenoids', 'Chlorophyll', 'Anthocyanins', 'Melanin'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Chlorophyll acts as a light absorber during photosynthesis and grants leaves their green pigment.',
  },
  {
    id: 'sci_6',
    question: 'How long does it take for light from the Sun to reach Earth?',
    options: ['8 seconds', '8 minutes', '8 hours', '8 days'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'medium',
    explanation: 'At 150 million kilometers away, sunlight travels approximately 8 minutes and 20 seconds to reach Earth.',
  },
  {
    id: 'sci_7',
    question: 'What is the approximate scientific age of the Universe?',
    options: ['4.5 billion years', '13.8 billion years', '20 billion years', '100 million years'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'medium',
    explanation: 'Cosmologic radiation measurements suggest the universe originated approximately 13.8 billion years ago compiling from the Big Bang.',
  },
  {
    id: 'sci_8',
    question: 'What primary atmospheric gas do green plants absorb to conduct photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
    correctAnswerIndex: 2,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Plants consume gaseous Carbon Dioxide (CO2) from surrounding air to convert to organic sugars during light reactions.',
  },
  {
    id: 'sci_9',
    question: 'What is the most abundant gas found in Earth\'s atmosphere?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
    correctAnswerIndex: 2,
    category: 'science',
    difficulty: 'medium',
    explanation: 'Nitrogen gas (N2) composes approximately 78% of dry atmosphere on Earth, followed by oxygen at 21%.',
  },
  {
    id: 'sci_10',
    question: 'What is the only metallic element that remains liquid at standard room temperatures?',
    options: ['Lead', 'Mercury', 'Gallium', 'Bromine'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Mercury (element symbol Hg) has a low melting point of -38.8°C, retaining liquid phase under ambient room conditions.',
  },
  {
    id: 'sci_11',
    question: 'Which legendary physicist formulated the Laws of Motion and Universal Gravitation?',
    options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Sir Isaac Newton formulated these mathematical frameworks in his classic work "Philosophiae Naturalis Principia Mathematica" in 1687.',
  },
  {
    id: 'sci_12',
    question: 'What is the chemical formula representing pure water molecule structures?',
    options: ['CO2', 'NaCl', 'H2O', 'O2'],
    correctAnswerIndex: 2,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Each molecule of water integrates two Hydrogen atoms bonded covalently to a single Oxygen core (H2O).',
  },
  {
    id: 'sci_13',
    question: 'What famous logarithmic scale measures the magnitude intensity of earthquakes?',
    options: ['Celsius scale', 'Kelvin scale', 'Richter scale', 'Beaufort scale'],
    correctAnswerIndex: 2,
    category: 'science',
    difficulty: 'easy',
    explanation: 'The Richter magnitude scale computes mechanical wave amplitude to calculate energy release from planetary tectonic fault slips.',
  },
  {
    id: 'sci_14',
    question: 'Which human blood type is considered the absolute universal donor?',
    options: ['A Positive', 'B Negative', 'AB Positive', 'O Negative'],
    correctAnswerIndex: 3,
    category: 'science',
    difficulty: 'medium',
    explanation: 'O Negative blood completely lacks external A, B, or Rh surface antigens, excluding immune rejections during transfusion.',
  },
  {
    id: 'sci_15',
    question: 'How many permanent dental teeth does a healthy adult human usually possess, including wisdom teeth?',
    options: ['28', '30', '32', '36'],
    correctAnswerIndex: 2,
    category: 'science',
    difficulty: 'easy',
    explanation: 'A healthy permanent adult dental structure includes 32 functional items: 8 incisors, 4 canines, 8 premolars, and 12 molars.',
  },
  {
    id: 'sci_16',
    question: 'What is the hardest mineral naturally occurring on planet Earth?',
    options: ['Steel', 'Diamond', 'Quartz', 'Titanium'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Diamond is an allotrope of carbon featuring tetrahedral atom bounds, rating 10 on Mohs scientific scale.',
  },
  {
    id: 'sci_17',
    question: 'The academic field of Botany represents the study of which domain?',
    options: ['Zoology', 'Botany/Plants', 'Geology', 'Meteorology'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Botany is a vital branch of biology documenting vegetation structures, physiology, and ecological distribution.',
  },
  {
    id: 'sci_18',
    question: 'What is the standard unit of measurement representing electric resistance?',
    options: ['Volt', 'Ampere', 'Watt', 'Ohm'],
    correctAnswerIndex: 3,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Electric resistance is registered in Ohms, defined by Ohm\'s Law correlating volts and current amperes.',
  },
  {
    id: 'sci_19',
    question: 'Which of the inner terrestrial planets in our Solar System is widely styled the "Red Planet"?',
    options: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
    correctAnswerIndex: 1,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Mars appears ruddy from outer space due to high percentage concentrations of oxidized iron minerals on its dry crust.',
  },
  {
    id: 'sci_20',
    question: 'Which subatomic element carries a negative electrical charge inside atomic structures?',
    options: ['Proton', 'Neutron', 'Electron', 'Quark'],
    correctAnswerIndex: 2,
    category: 'science',
    difficulty: 'easy',
    explanation: 'Electrons orbit outer boundaries of atomic nuclei, countering the positive charges exerted by protons within.',
  },

  // HISTORY & GEOGRAPHY (20 items)
  {
    id: 'hist_1',
    question: 'What is the capital city of Australia?',
    options: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'],
    correctAnswerIndex: 3,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Canberra was chosen as Australia\'s capital in 1908 as a compromise between rivals Sydney and Melbourne.',
  },
  {
    id: 'hist_2',
    question: 'Which empire built the spectacular Machu Picchu in modern-day Peru?',
    options: ['Aztecs', 'Mayans', 'Incas', 'Olmecs'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'medium',
    explanation: 'Machu Picchu is a 15th-century Inca citadel nestled high in the Andean mountain range.',
  },
  {
    id: 'hist_3',
    question: 'Who was the first President of the United States?',
    options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'easy',
    explanation: 'George Washington served as president from 1789 to 1797 after leading the Continental Army to victory.',
  },
  {
    id: 'hist_4',
    question: 'In what year did the Berlin Wall fall, signaling the impending dissolution of the Iron Curtain?',
    options: ['1985', '1989', '1991', '1993'],
    correctAnswerIndex: 1,
    category: 'history',
    difficulty: 'medium',
    explanation: 'The demolition of the Berlin Wall officially began on November 9, 1989, leading to the reunification of Germany.',
  },
  {
    id: 'hist_5',
    question: 'Which is the largest ocean on Earth?',
    options: ['Atlantic Ocean', 'Indian Ocean', 'Southern Ocean', 'Pacific Ocean'],
    correctAnswerIndex: 3,
    category: 'history',
    difficulty: 'easy',
    explanation: 'The Pacific Ocean is the largest and deepest water body, spanning over 63 million square miles (one-third of Earth\'s surface).',
  },
  {
    id: 'hist_6',
    question: 'Which country is historically known as "the land of the rising sun"?',
    options: ['China', 'Japan', 'South Korea', 'Vietnam'],
    correctAnswerIndex: 1,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Japan is widely called Nihon or Nippon, which translates literally to "the origin of the sun" or "the land of the rising sun".',
  },
  {
    id: 'hist_7',
    question: 'Which river is geographically identified as the longest river in the world?',
    options: ['Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River'],
    correctAnswerIndex: 1,
    category: 'history',
    difficulty: 'medium',
    explanation: 'The Nile is historically considered the longest river, stretching roughly 6,650 km across northeastern Africa.',
  },
  {
    id: 'hist_8',
    question: 'In which sovereign country is the white marble Taj Mahal monument located?',
    options: ['Pakistan', 'India', 'Bangladesh', 'Nepal'],
    correctAnswerIndex: 1,
    category: 'history',
    difficulty: 'easy',
    explanation: 'The Taj Mahal resides on the bank of the Yamuna River in Agra, India, commissioned by Shah Jahan in 1632.',
  },
  {
    id: 'hist_9',
    question: 'Which continent holds the crown as the largest by total terrestrial landmass?',
    options: ['Africa', 'North America', 'Europe', 'Asia'],
    correctAnswerIndex: 3,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Asia spans roughly 17.2 million square miles, comprising around 30% of global land allocation.',
  },
  {
    id: 'hist_10',
    question: 'Greenland, the largest island in the world, is politically associated with which European state?',
    options: ['Canada', 'Denmark', 'Norway', 'Iceland'],
    correctAnswerIndex: 1,
    category: 'history',
    difficulty: 'medium',
    explanation: 'Greenland is politically organized as an autonomous constituency inside the Kingdom of Denmark.',
  },
  {
    id: 'hist_11',
    question: 'Which historic navigator steered the European discovery of trade links to the Americas in 1492?',
    options: ['Vasco da Gama', 'Ferdinand Magellan', 'Christopher Columbus', 'Marco Polo'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Christopher Columbus sailed westward on behalf of the Spanish crown, landing in Caribbean archipelagos.',
  },
  {
    id: 'hist_12',
    question: 'In what year did World War I hostilities officially end through the signing of the initial armistice?',
    options: ['1914', '1917', '1918', '1922'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'medium',
    explanation: 'Allied forces signed the armistice with Germany ending hostilities at 11:00 am on November 11, 1918.',
  },
  {
    id: 'hist_13',
    question: 'What is the sovereign capital city of the Republic of France?',
    options: ['London', 'Berlin', 'Rome', 'Paris'],
    correctAnswerIndex: 3,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Paris serves as France\'s leading political, cultural, and geographic hub on the Seine River.',
  },
  {
    id: 'hist_14',
    question: 'Which nation possesses more geographic natural lakes than any counterpart worldwide?',
    options: ['United States', 'Russia', 'Canada', 'Brazil'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'medium',
    explanation: 'Over 60% of absolute global lakes reside inside Canada; freshwater covers massive portions of its state bounds.',
  },
  {
    id: 'hist_15',
    question: 'Who was the final ruling active Pharaonic Queen of Egyptian Ptolemy lands?',
    options: ['Nefertiti', 'Hatshepsut', 'Cleopatra', 'Arsinoe'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Cleopatra VII Philopator ruled Egypt dynamically, establishing diplomatic alliances with Rome before its transition to empire.',
  },
  {
    id: 'hist_16',
    question: 'What is the smallest autonomous independent state in the world by land measurement?',
    options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctAnswerIndex: 1,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Vatican City is an enclave microstate in Rome measuring just 0.49 square km, managed by the Holy See.',
  },
  {
    id: 'hist_17',
    question: 'Which civilization initially constructed the monumental Colosseum in Rome?',
    options: ['Ancient Greeks', 'Ancient Egyptians', 'Romans', 'Byzantines'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'easy',
    explanation: 'The Flavian Amphitheatre (Colosseum) was designed and raised by the Romans in 72–80 AD.',
  },
  {
    id: 'hist_18',
    question: 'Which European country margins Portugal on the Iberian Peninsula?',
    options: ['France', 'Italy', 'Spain', 'Andorra'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Portugal lies on the Atlantic margin of the Iberian peninsula, partitioned solely by Spain on land.',
  },
  {
    id: 'hist_19',
    question: 'Which mountain peak represents the highest elevation point above sea level on Earth?',
    options: ['K2', 'Mount Kilimanjaro', 'Mount Everest', 'Denali'],
    correctAnswerIndex: 2,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Mount Everest reaches 8,848.86 meters high, located on the border between Nepal and Tibet.',
  },
  {
    id: 'hist_20',
    question: 'Who authored the historical, intimate diary recounting years spent hiding from German forces in Amsterdam?',
    options: ['Helen Keller', 'Anne Frank', 'Florence Nightingale', 'Marie Curie'],
    correctAnswerIndex: 1,
    category: 'history',
    difficulty: 'easy',
    explanation: 'Anne Frank documented her life in an annex on Prinsengracht from 1942 until discovered in August 1944.',
  },

  // SPORTS & ENTERTAINMENT (20 items)
  {
    id: 'sport_1',
    question: 'How many players are on the field for one team during a standard soccer match?',
    options: ['9', '10', '11', '12'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Each side plays with exactly 11 players, which includes ten outfielders and one goalkeeper.',
  },
  {
    id: 'sport_2',
    question: 'Which movie won the first-ever Academy Award for Best Picture in 1929?',
    options: ['Wings', 'Metropolis', 'The Jazz Singer', 'Sunrise'],
    correctAnswerIndex: 0,
    category: 'sports',
    difficulty: 'hard',
    explanation: '"Wings", a silent war epic about WWI fighter pilots, remains the only purely silent film to win Best Picture.',
  },
  {
    id: 'sport_3',
    question: 'Which country has won the most FIFA World Cup titles in men\'s soccer?',
    options: ['Germany', 'Italy', 'Argentina', 'Brazil'],
    correctAnswerIndex: 3,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Brazil holds the record with five men\'s FIFA World Cup accolades (1958, 1962, 1970, 1994, and 2002).',
  },
  {
    id: 'sport_4',
    question: 'Who painted the famous masterpiece "The Starry Night"?',
    options: ['Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dalí'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Vincent van Gogh painted "The Starry Night" in June 1889 from his asylum room window at Saint-Rémy-de-Provence.',
  },
  {
    id: 'sport_5',
    question: 'Which athlete has won the most Olympic gold medals of all time?',
    options: ['Usain Bolt', 'Michael Phelps', 'Larisa Latynina', 'Carl Lewis'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'medium',
    explanation: 'U.S. swimmer Michael Phelps is the most decorated Olympian, earning 23 gold medals (and 28 medals total).',
  },
  {
    id: 'sport_6',
    question: 'Which of the following fantasy worlds was created by author J.R.R. Tolkien?',
    options: ['Narnia', 'Middle-earth', 'Westeros', 'Hogwarts'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Middle-earth is the central legendary setting of Tolkien\'s famous classics, including The Hobbit and The Lord of the Rings.',
  },
  {
    id: 'sport_7',
    question: 'Which classic actor portrayed the legendary Don Vito Corleone in the 1972 cinematic masterpiece "The Godfather"?',
    options: ['Al Pacino', 'Marlon Brando', 'Robert De Niro', 'Dustin Hoffman'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'medium',
    explanation: 'Marlon Brando took home the Academy Award for Best Actor for his immortalization of Vito Corleone.',
  },
  {
    id: 'sport_8',
    question: 'How many rings are interlinked on the official Olympic symbol and flag?',
    options: ['3', '4', '5', '6'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Five rings of distinct color represent five inhabited regions involved in global competitive sportsmanship.',
  },
  {
    id: 'sport_9',
    question: 'Who stands as the highest absolute direct scorer in modern NBA history?',
    options: ['Michael Jordan', 'LeBron James', 'Kareem Abdul-Jabbar', 'Kobe Bryant'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'medium',
    explanation: 'LeBron James eclipsed Kareem Abdul-Jabbar\'s historic 38,387 career points in February 2023.',
  },
  {
    id: 'sport_10',
    question: 'Which legendary 1980s music artist is universally dubbed the "King of Pop"?',
    options: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Justin Timberlake'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Michael Jackson earned the title of King of Pop with Thriller, the top-selling album in music publication records.',
  },
  {
    id: 'sport_11',
    question: 'In standard board chess, which exact piece is permitted to jump or hurdle other blocking items?',
    options: ['Rook', 'Knight', 'Bishop', 'Queen'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'The Knight travels in distinct L-shaped patterns, bypassing standard vertical or diagonal blocking limitations.',
  },
  {
    id: 'sport_12',
    question: 'Which heavy-metal rock band authored the iconic albums "Master of Puppets" (1986)?',
    options: ['Iron Maiden', 'Metallica', 'Led Zeppelin', 'Guns N\' Roses'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Metallica composed Master of Puppets, widely recorded as a monumental pioneering document in thrash metal history.',
  },
  {
    id: 'sport_13',
    question: 'Which historic grass courts host the pristine annual Wimbledon tournament?',
    options: ['Golf', 'Cricket', 'Tennis', 'Badminton'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Tennis matches take place on natural grass courts at the All England Club in London.',
  },
  {
    id: 'sport_14',
    question: 'Who co-designed and launched the animated persona of "Mickey Mouse" in 1928?',
    options: ['Charles Schulz', 'Stan Lee', 'Walt Disney', 'Hayao Miyazaki'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Walt Disney alongside cartoonist Ub Iwerks produced Mickey Mouse, debuting in the synchronized sound cartoon Steamboat Willie.',
  },
  {
    id: 'sport_15',
    question: 'Who is the green-clad legendary protagonist of Nintendo\'s "The Legend of Zelda"?',
    options: ['Zelda', 'Link', 'Mario', 'Ganon'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Link is the chosen hero of Hyrule, wielding the Master Sword to defend structural segments of the Triforce from Ganon.',
  },
  {
    id: 'sport_16',
    question: 'Which nation hosts the primary course layout of the prestigious annual cycling race, "Tour de France"?',
    options: ['Spain', 'Italy', 'France', 'Germany'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Tour de France routes primarily cross cities, passes, and finish lines inside France, ending on the Champs-Élysées.',
  },
  {
    id: 'sport_17',
    question: 'Which progressive English rock band produced the classic concept LP "The Dark Side of the Moon"?',
    options: ['The Beatles', 'Pink Floyd', 'The Rolling Stones', 'Queen'],
    correctAnswerIndex: 1,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Pink Floyd launched "The Dark Side of the Moon" in 1973, setting records for continuous charts duration.',
  },
  {
    id: 'sport_18',
    question: 'What is the maximum absolute possible points attainable in a single frame of standard 10-pin bowling?',
    options: ['10', '20', '30', '300'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'medium',
    explanation: 'Accumulating three consecutive strikes grants 30 absolute points inside a single frame tracking score multiplication.',
  },
  {
    id: 'sport_19',
    question: 'Which sandbox software title remains the highest-selling video game of all time?',
    options: ['Grand Theft Auto V', 'Tetris', 'Minecraft', 'Wii Sports'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'Minecraft leads global historical software distributions with more than 300 million items sold across systems.',
  },
  {
    id: 'sport_20',
    question: 'Which massive cinematic universe centers on Luke Skywalker, Han Solo, and Darth Vader?',
    options: ['Star Trek', 'Marvel Cinematic Universe', 'Star Wars', 'The Lord of the Rings'],
    correctAnswerIndex: 2,
    category: 'sports',
    difficulty: 'easy',
    explanation: 'George Lucas engineered the epic Star Wars space fantasy franchise, debuting its initial cosmic adventure in 1977.',
  },
];
